documentation-language = "en"
documentation-readiness-level = "ODRL-3"
function = "This OpenSCAD script prints a A 2-part, hinged, bolt-on holder/fixture for affixing a small packaged sensing device (in this case a custom WIMU) to a round shaft or bar allowing it to be easily attached to golf clubs, tennis racquets, pipes, cylindrical bar stock, walking sticks etc.\r\n\r\nVersion:\r\n2.3.2\r\n\r\nDate:\r\n2012-03-02\r\n\r\nTo Do:\r\nNothing\r\n\r\nNote:\r\nyou will need the mouse_ears_test.scad file in the same folder asthis file for the mouse ears to compile properly\r\nyou will need the pivot_1_0.scad file in the same folder as this file for the hinge and bolt hole to compile properly\r\nyou will need the rounded_cuboid_2_5.scad file in the same folder as this file for the object to compile properly\r\n\r\nChanges from previous versions:\r\nv2.3.4\r\n - \tchange shaft diameter to 30mm\r\n\r\nv2.3.4\r\n - \tfix small elevation error for cap\r\n - \tadded some tolerance to make inserting insert possible!\r\n\r\nv2.3.3\r\n - \tadded nubs to help locate cap onto top\r\n - \tadded extra insert piece to allow device to be inserted from bottom\r\nv2.3.2\r\n - \tadded cap\r\nv2.3.1\r\n - \treduced tolerances for better fit (from 0.45 to 0.35)\r\nv2.3\r\n - \tremoved deprecated variables\r\n - \tnew variable \"arm_length\" determines how much extra space there is for the hinge and bolt hole\r\n- \tnew variable \"cutout_support_thickness\" allows you to specify width of walls left in areas where support are needed such as under the arch for the shaft and the cutouts on the side of the holder\r\nv2.2\r\n - \tSwitched to newer rounded cuboid module (v2.5) which makes positioning easier!\r\n - \tadd cutouts for connections to held object\r\nv2.1\r\n - \tadded pivot_1_0.scad module for hinge\r\n - \tCan now generate bottom half\r\n - \tAdded control variables to control whether top, bottom or both are generated and whether or not they are stacked or have mouse ears\r\n - \tAdded captive nut on top half\r\n - \tMore parametric!\r\n - \tRotated held object 90 degrees so I can make holes for uUSB port which would have been blocked by bolt and hinge otherwise\r\nv2.0\r\n - \tCompletely remade parametric version in openscad based on alex's strap holder\r\nv1.1\r\n - \tchanged some sizes to make it easier to use without rework\r\nv1.0\r\n - \tOriginal non-parametric autocad version"
image = "https://thingiverse-rerender-new.s3.amazonaws.com/renders/c1/1d/f1/01/87/2012-02-23_WIMUv3_club_holder_v2.3.3-Kieran-cap_display_large.jpg"
license = "CC-BY-SA-4.0"
licensor = "M_G"
name = "Parametric Club Holder v2"
okhv = "OKH-LOSHv1.0"
part = []
repo = "https://www.thingiverse.com/thing:17600"
software = []
technology-readiness-level = "OTRL-4"
upload-method = "auto"
version = "1.0.0"

[__meta]
created-at = "2012-02-14T17:15:16+00:00"
last-visited = "2022-02-25T11:00:02.616920+00:00"
owner = "M_G"
repo = "https://www.thingiverse.com/thing:17600"
source = "thingiverse.com"

[specific-api-data]
